### ISSUE TITLE
python-visual not available on Ubuntu 18.04

### ISSUE THREAD

**Issue by subodh-malgonde** [ENSTABretagneRobotics/razor_imu_9dof#42]
Hi,

My OS is Ubuntu 18.04 (Bionic Beaver) and I am using ROS Melodic. Currently the `python-visual` package is not available for this OS. Hence I am not able to use the 3D Visualization GUI tool. Is there an alternative to python-visual or a workaround for this problem?

**Comment by Maik93** [comment]
Same problem. Have you found a solution?

**Comment by zlewe** [comment]
The alternative provided in #47 works well for this purpose.

**Comment by Maik93** [comment]
I cannot create the new environment suggested in that post, too many dependencies seems unavailable for me... Can you please share your Python environment .yaml file if you have installed it on your local machine?
