### ISSUE TITLE
Error in running for "roslaunch razor_imu_9dof razor-pub-and-display.launch"

### ISSUE THREAD

**Issue by ycean** [ENSTABretagneRobotics/razor_imu_9dof#47]
There are two issues i am facing right now. After I entering roslaunch razor_imu_9dof razor-pub-and-display.launch, the error message came out as below~

SUMMARY
========

PARAMETERS
 * /imu_node/accel_x_max: 250.0
 * /imu_node/accel_x_min: -250.0
 * /imu_node/accel_y_max: 250.0
 * /imu_node/accel_y_min: -250.0
 * /imu_node/accel_z_max: 250.0
 * /imu_node/accel_z_min: -250.0
 * /imu_node/calibration_magn_use_extended: False
 * /imu_node/gyro_average_offset_x: 0.0
 * /imu_node/gyro_average_offset_y: 0.0
 * /imu_node/gyro_average_offset_z: 0.0
 * /imu_node/imu_yaw_calibration: 0.0
 * /imu_node/magn_ellipsoid_center: [0, 0, 0]
 * /imu_node/magn_ellipsoid_transform: [[0, 0, 0], [0, 0...
 * /imu_node/magn_x_max: 600.0
 * /imu_node/magn_x_min: -600.0
 * /imu_node/magn_y_max: 600.0
 * /imu_node/magn_y_min: -600.0
 * /imu_node/magn_z_max: 600.0
 * /imu_node/magn_z_min: -600.0
 * /imu_node/port: /dev/ttyusb
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    display_3D_visualization_node (razor_imu_9dof/display_3D_visualization.py)
    imu_node (razor_imu_9dof/imu_node.py)

auto-starting new master
process[master]: started with pid [4547]
ROS_MASTER_URI=http://192.168.0.26:11311

setting /run_id to 1372f8ca-1ddb-11e9-b326-98541b9f9cdc
process[rosout-1]: started with pid [4560]
started core service [/rosout]
process[imu_node-2]: started with pid [4563]
process[display_3D_visualization_node-3]: started with pid [4564]
**Traceback (most recent call last):
  File "/opt/ros/kinetic/share/razor_imu_9dof/nodes/display_3D_visualization.py", line 31, in <module>
    from visual import *
ImportError: No module named visual**
[display_3D_visualization_node-3] process has died [pid 4564, exit code 1, cmd /opt/ros/kinetic/share/razor_imu_9dof/nodes/display_3D_visualization.py __name:=display_3D_visualization_node __log:=/home/test/.ros/log/1372f8ca-1ddb-11e9-b326-98541b9f9cdc/display_3D_visualization_node-3.log].
log file: /home/test/.ros/log/1372f8ca-1ddb-11e9-b326-98541b9f9cdc/display_3D_visualization_node-3*.log
[INFO] [1548116239.024456]: Reconfigure request for yaw_calibration: 0
[INFO] [1548116239.024619]: Set imu_yaw_calibration to 0
[INFO] [1548116239.036369]: Opening /dev/ttyusb...
**[ERROR] [1548116239.036544]: IMU not found at port /dev/ttyusb. Did you specify the correct port in the launch file?**
[imu_node-2] process has finished cleanly
log file: /home/test/.ros/log/1372f8ca-1ddb-11e9-b326-98541b9f9cdc/imu_node-2*.log
^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

The visual import not found, and the sensor port wasn't detected from the error message I had.
I did check the port of the FSM-9 IMU I attached with, the error still coming out.

**Comment by AhmedAbdlhamid** [comment]
Hello, 
Yea this is bascially becase visual library is deprecated. You can use vpython instead. Thr problem lies in vpython is supported with python3. And when using ROS you are using python2. 
There is a work around , first launch the razor-pub.node without visualization then you can install anaconda and import the following yml to create an environment. And then you go to this virtual environment and run python3 visualization script. The modified visulization node and the anaconda environment can be found here https://github.com/AhmedAbdlhamid/IMU_Razor9DOF

Regards, the port check you have the corrext port and remember to give permission to it in terminal by
Sudo chmod a+rw /dev/ttyACM*
The /dev/ttyACM* is the name of the port which  IMU is using.

**Comment by phdeshmane** [comment]
Hi, the link in the comment that is supposed to resolve this issue (https://github.com/lebarsfa/visual/tree/bionic) goes to a 404 page not found. 
I really need the visualization to work in ROS for our robot car, what was supposed to be on this page?

# For Ubuntu 18.04, install https://github.com/lebarsfa/visual/tree/bionic

**Comment by phdeshmane** [comment]
Hi, 
I am trying to do the visual library install to enable 3D-visualization in ROS for Ubuntu 18.04 from the following instruction in the README.
# For Ubuntu 18.04, install https://github.com/lebarsfa/visual/tree/bionic

I followed the INSTALL.txt instructions below from the visual repository above. However, when I run the "make" command (after ./configure) I get this error:

Making all in site-packages/visual
make[1]: Entering directory '/home/jetson/visual/site-packages/visual'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/jetson/visual/site-packages/visual'
Making all in site-packages/vis
make[1]: Entering directory '/home/jetson/visual/site-packages/vis'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/jetson/visual/site-packages/vis'
Making all in src
make[1]: Entering directory '/home/jetson/visual/src'
Compiling ./core/util/extent.cpp ...
Makefile:232: recipe for target 'extent.lo' failed
make[1]: *** [extent.lo] Error 1
make[1]: Leaving directory '/home/jetson/visual/src'
Makefile:451: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

How do I get around this? Please help as we really need the 3D-visualization for our robot car. 

I was following the instructions from the INSTALL.txt file pasted below and the error occurred after executing "make" command. 

QUICK INFO for Ubuntu 18.04:

sudo apt-get update
sudo apt-get install libgtkglextmm-x11-1.2-dev libglademm-2.4-dev python-dev python-pip python-numpy python-fonttools libboost-python-dev libboost-numpy-dev libboost-thread-dev libboost-signals-dev
sudo pip install Polygon2 ttfquery
wget https://github.com/vpython/vpython.docs/archive/master.zip
unzip -q master.zip
mv -f vpython.docs-master docs
sh ./autogen.sh
./configure
make
sudo make install
sudo rm -Rf /usr/local/lib/python2.7/dist-packages/visual
sudo mv -f /usr/local/lib/python2.7/site-packages/visual /usr/local/lib/python2.7/dist-packages/
sudo rm -Rf /usr/local/lib/python2.7/dist-packages/vis
sudo mv -f /usr/local/lib/python2.7/site-packages/vis /usr/local/lib/python2.7/dist-packages/
